name = "worker-template"
type = "javascript"
zone_id = ""
account_id = "c8526a45c47706d6c69f8d997004bd7a"
route = ""
workers_dev = true
compatibility_date = "2021-12-19"
kv_namespaces = [
    # { binding = "NAMESPACE", id = "id" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
